#!/usr/bin/env bash
PC_APIURL="https://api2.prismacloud.io"
PC_ACCESSKEY="c8759d68-af67-4cb4-b349-ceb7b5930532"
PC_SECRETKEY="F7U4px2SUfmzp+i+XZOV47TB+gU="
TL_CONSOLE="https://us-east1.cloud.twistlock.com/us-2-158313609"
TL_USER="c8759d68-af67-4cb4-b349-ceb7b5930532"
TL_PASSWORD="F7U4px2SUfmzp+i+XZOV47TB+gU="
